### ISSUE TITLE
With no arguments, going $HOME as cd does

### ISSUE THREAD

**Issue by livibetter** [ooesili/qfi#3]
## Feature request

I'd like `qfi` to be able to switch to `$HOME` when no arguments are given instead of the following error message:

```
$ qfi
qfi: no target specified
Usage: qfi TARGET
[...]
```

It doesn't have to be default action, it can be enabled by configuration. But as I looked around, I realized there is no actual configuration file for settings as far as I could tell in current qfi.

If @ooesili doesn't like it to be default action, maybe we can have a special symbolic link under `$HOME/.config/qfi` along with other normal targets? Perhaps `$HOME/.config/qf/.home` or `.default`?

Of course, `.home` doesn't need to be a symlink, a normal file would do. But `.default` could bring in some other potentials. There might be some people would like to be able to switch to specific directory and `.default` would link to it.

Anyway, this is what I have on this request.

## Why requesting

When using `cd` command without any arguments, it sends you to `$HOME` and I am extremely accustomed to that. I think that's probably because I also used to do that with my switching script `g` (now alias to qfi, as I ditched my own).

From time to time, I would enter:

```sh
$ g  # enter without any arguments
```

In late June, I had thought about creating a feature request, but didn't do it. I just lived with it. In fact, I'd actually thought of wrapping with another Bash function or script to check the arguments, but I never did do that, because I don't feel that's worth.

Now, it happened again. That's why I finally decided to open this issue for it.

## `cd(1p)`

The following is a quote of the relevant `cd` behaviors from *POSIX Programmer's Manual*:

> 1. If  no  directory operand is given and the HOME environment variable is empty or undefined, the default behavior is implementation-defined and no further steps shall be taken.
>
> 2. If no directory operand is given and the HOME environment variable is set to a non-empty value, the  cd  utility  shall  behave  as if the directory named in the HOME environment variable was specified as the directory operand.

----

Off-topic: I'd wish I could code Perl if this feature request gets accepted, so I could contribute in codes, but I really don't know anything about Perl, so all I could do is hoping this can be accepted and implemented.

**Comment by livibetter** [comment]
I am closing this since I've it from the commit.

**Comment by ooesili** [comment]
I have plans to move configuration from a directory of symlinks to a proper configuration file. I will definitely add this as an option when that point comes.

**Comment by livibetter** [comment]
@ooesili I actually quite like the symlinks to be honest, because I can check and edit with shell if I want to, but I'm fine with configuration file. One file or many symlinks, that's the personal preference. No double single file is cleaner.

**Comment by ooesili** [comment]
The thing that I would like about a configuration file is that it would be easier to cleaner to check into a source control system, and there would be space to customize other aspects of the program, like the aforementioned "default" target.

Also, right now, if I ran `qfi -a i3 ~/.i3/config`, the resulting link would be to `/home/ooesili/.qfi/.config`. If I were to ever rename my user on my machine, or copy the configuration to a different computer with a different username, the links would break. A configuration file would allow me to store `~/.i3/config`, making the configuration portable.

**Comment by livibetter** [comment]
On Sat, Jan 2, 2016 at 1:06 PM, Wesley Merkel <notifications@github.com> wrote:
> The thing that I would like about a configuration file is that it would be easier to cleaner to check into a source control system, [...]

I haven't thought about putting them into rcs, now I can see why.

> Also, right now, if I ran qfi -a i3 ~/.i3/config, the resulting link would be to /home/ooesili/.qfi/.config. If I were to ever rename my user on my machine, or copy the configuration to a different computer with a different username, the links would break. A configuration file would allow me to store ~/.i3/config, making the configuration portable.

And this really is a great point for the portability.

**Comment by livibetter** [comment]
I'm closing this to keep my Issues list clean, if anyone wants this please create a new one.
