### ISSUE TITLE
Optional TARGET in addition

### ISSUE THREAD

**Issue by livibetter** [ooesili/qfi#4]
I'd like to see:

```
qfi [-a|-m] TARGET FILENAME
```

to be broken down to:

```
qfi -a [TARGET] FILENAME
qfi -m TARGET FILENAME
```

That is the `TARGET` would be optional for adding new targets. When qfi gets only one argument, it would get the base name of `FILENAME`, or just remove directories part, as the `TARGET`.

My reason for making `TARGET` optional is, from `ln(1)`:

```
 ln [OPTION]... TARGET                  (2nd form)
```

I am used to it, and qfi's syntax take much more typing since most ot time the two arguments are exactly the same. As the tab-completion isn't activated after `-a`, I would have to enter the filename as `TARGET`, then it would be activated for `FILENAME`.

This isn't really a very important need, because I hardly add anything these days, but it would be nice to see it happening.

**Comment by livibetter** [comment]
@ooesili what's your take on this? If you don't want to do it, I can understand, I just want to close this. Or if you agree on this, but don't want to do it yourself, I can attempt it with my zero-skilled Perl.

**Comment by ooesili** [comment]
I'm going to work on this tonight. My apologies for not working on this repo for so long. I'll try to be much more responsive to feedback and feature requests.

**Comment by ooesili** [comment]
Done! 15a2d324b1bdcb9411bc354178ac0fd071c32019
