### ISSUE TITLE
Status of Perl version?

### ISSUE THREAD

**Issue by livibetter** [ooesili/qfi#5]
@ooesili Is it deprecated? Still maintained? Accepting feature requests, bugfixing?

**Comment by ooesili** [comment]
I'm no longer going to maintain that version. It's been a real pain trying to make a good way to install it on other systems, particularly OS X. The directories where libraries and such live differ from system to system, so I would have to make a seperate OS specific package for each. Such as a homebrew formula for OS X, a apt package for Debian/Ubuntu, a ebuild script for Gentoo, an RPM package for... you get the idea.

The Go rewrite is pretty much the same, as far as usage goes, but it will be much easier to distribute and install, which will save people time, which is the whole point of this project.

I am totally still taking feature requests and bug fixes, but they should be for the Go version only. I will not be putting any effort into maintaining the old Perl version. The rewrite is not totally done yet, but it's pretty close. I should have in a state that I am happy with within a week. I'll push up a new tag when the time comes, but until then things will still be changing quite a bit.

Let me know if you have any other questions.

**Comment by livibetter** [comment]
I wish you were rewriting in C since I don't have Go and I don't want to install it. Anyway, I will still keep and use the Perl version as long as I can.

Closing.

**Comment by ooesili** [comment]
You won't need to install go to use it! :smile:

Go compiles statically linked binaries by default, so you'll just be able to download the binary from the release page, and you'll be good to go.

**Comment by livibetter** [comment]
@ooesili Glad to hear that! I'll be waiting for your first release of Go version. Any ETA?

Frankly, that -- binary package -- has never come to my mind when I use code from GitHub or any source hosting, it seems clone and compile are the only way to go (no pun intended). In fact, more like the only legit way to use such codes.

By the way, since you mentioned about Gentoo ebuild, does that mean you get a plan to get qfi into official Portage tree? If so, make sure to have an additional binary package if it doesn't against any policy, I could even install via Portage. I really hope qfi can be available for major distributions. It's simple and just right features of what I actually need.

**Comment by ooesili** [comment]
In the Go ecosystem, it seems to be pretty common to distribute programs as binaries, which I agree is a little different. Pretty much all of the biggest programs out right now written in Go are released as compiles binaries, like etcd, docker, syncthing, gogs, kubernetes, and consul.

I didn't have any plans to make an ebuild for qfi, as I am not a regular Gentoo user. The goal with the Go rewrite is that making distro packages wouldn't really be necessary. All a user will have to do is download the binary, throw in their `$PATH`, and add a line to their `~/.bashrc`.

Of course, installation through a familiar package manager would be ideal. Once I have all of the features rewritten and everything feels stable, I'll look into setting up some distro packages. The ease of installation with the rewritten version should make packaging much easier. It seemed like such a daunting task before, with the weird build system that I was using with Perl.

I'm hoping to have a release out within a week. I started using Pivotal tracker to manage the project, so you can keep up with what I'm doing [here](https://www.pivotaltracker.com/n/projects/1506838), if you would like. I'm going to add that link to the README soon.

**Comment by livibetter** [comment]
On Sat, Jan 2, 2016 at 1:33 PM, Wesley Merkel <notifications@github.com> wrote:
> In the Go ecosystem, it seems to be pretty common to distribute programs as
> binaries, which I agree is a little different. Pretty much all of the
> biggest programs out right now written in Go are released as compiles
> binaries, like etcd, docker, syncthing, gogs, kubernetes, and consul.

As you can tell, I have zero knowledge of any of them, although I've
heard of "Docker" a lot, really a lot.

> I didn't have any plans to make an ebuild for qfi, as I am not a regular
> Gentoo user. The goal with the Go rewrite is that making distro packages
> wouldn't really be necessary. All a user will have to do is download the
> binary, throw in their $PATH, and add a line to their ~/.bashrc.

No worries, I have a directory specially made for storing binary
package downloads.

**Comment by ooesili** [comment]
[Tada!](https://github.com/ooesili/qfi/releases/tag/v0.5.0) Let me know if you encounter any problems.

**Comment by livibetter** [comment]
@ooesili I am using it, looks good to me, but I am only switching.

By the way, does Go have special library? I meant since it's binary, if there is no some libgo-something to link against, I think dynamically linked might still also work. 3MB for a statically linked build is fine, but if dynamically linked can also work, why not, right?

Would you mind build one for me and attach here, so I can see if it works?

**Comment by ooesili** [comment]
So, there is no libgo or anything like that. The newest minor version of Go (1.5) included support for creating dynamic libraries and executables ([see this slideshow](https://talks.golang.org/2015/state-of-go-may.slide#13)). However, the computer running the binary must already have the Go standard library compiled as a shared libraries. This complicates distribution, which is what I'm trying to avoid (there is a reason that no other Go projects distribute their applications this way). Maybe in the future it will be more feasible.

I played around with some of the linker flags and eventually got a dynamic executable, but it was actually larger than the static one by ~100KB. I did find the `-s` linker flag which disables the symbol table on the executable, which shrank the linux/amd64 binary by over a megabyte down to 2MB. I've added that flag to the Makefile, so the next release should be a bit smaller.

The fact is, the binaries produced by the Go compiler contain Go's entire runtime system, including its garbage collector and scheduler, so the binaries are going to be quite a bit meatier than a C executable. I'll do some research on ways to shrink the binaries a little more, but don't hold your breath :sweat_smile:

**Comment by livibetter** [comment]
@ooesili I just went to take a look of Go, I didn't know now it can be built without GCC. How long does it take to build Go with Go binary on your computer?

I am consider installing Go via Portage once 1.5 is stable and bootstrapping using Go compiler. From the look of go-bootstrap package, it's still 1.4.2 and still has C. Guess another couple of years, I shall have Go via Portage without bothering GCC (not kidding). I think I can still install it since it's not like I need to re-emerge GCC.

I couldn't remember when I turned on go USE flag of GCC, just to try out. Of course, it's off now.

Should I do it? If I do, I can try more projects here on GitHub. There are quite some projects I have to pass just because I didn't want to install Go.

**Comment by ooesili** [comment]
I just build Go from source using an existing 1.5.2 installation and it took 8m7.787s on a this:
```
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 69
Model name:            Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
Stepping:              1
CPU MHz:               1174.765
CPU max MHz:           2700.0000
CPU min MHz:           800.0000
BogoMIPS:              4001.89
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              3072K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow
vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt
```

You could always use vagrant or just a virtual machine if you wanted to play around with it without getting your system dirty.

**Comment by livibetter** [comment]
@ooesili I don't think my computer would do good. I am hoping some Gentoo dev would write an ebuild for Go binary release. As 1.5 can do dynamically, there is a hope, so I must wish Go goes bigger, that's my wish for 2016.

But for now, I stick with your binary release.

**Comment by livibetter** [comment]
I just installed Go binary at `$HOME`, which was ridiculously easy, just put it somewhere, then set up `GOROOT` and `GOPATH`, then modify `PATH` for bin directories under those two, done.

I am going to explore Go packages, wish I had saved links on those I'd found interesting.
